ibot:
  separate_head: true
train:
  batch_size_per_gpu: 16
  dataset_path: ImageNetCervicalNoPave:split=TRAIN:root=/projects/skinder@xsede.org/cervix_datasets/official/no_pave/data/root:extra=/projects/skinder@xsede.org/cervix_datasets/official/no_pave/data/extra
  centering: "centering"
student:
  arch: vit_base
  patch_size: 14
  drop_path_rate: 0.2
  ffn_layer: mlp
  pretrained_weights: '/scratch/alpine/skinder@xsede.org/cervix_dinov2/outputs/no_pave/imagenet/dinov2_vitb14_reg4_pretrain.pth'
  block_chunks: 0
  layerscale: 1.0
  num_register_tokens: 4
teacher:
  momentum_teacher: 0.994
  warmup_teacher_temp_epochs: 20
optim:
  epochs: 100
  warmup_epochs: 10
  base_lr: 4.0e-04  # learning rate for a batch size of 1024
  layerwise_decay: 1.0
  freeze_last_layer_epochs: 100
crops:
  global_crops_size: 518
  local_crops_size: 98