ibot:
  separate_head: true
train:
  batch_size_per_gpu: 32
  dataset_path: ImageNetCervicalPerformance:split=TRAIN:root=/projects/skinder@xsede.org/cervix_datasets/official/performance/data/root:extra=/projects/skinder@xsede.org/cervix_datasets/official/performance/data/extra
  centering: "centering"
student:
  arch: vit_large
  patch_size: 14
  drop_path_rate: 0.2
  ffn_layer: swiglufused
  block_chunks: 4
  num_register_tokens: 4
teacher:
  momentum_teacher: 0.994
  warmup_teacher_temp_epochs: 20
optim:
  epochs: 100
  warmup_epochs: 10
  base_lr: 0.001  # learning rate for a batch size of 1024
  layerwise_decay: 1.0
  freeze_last_layer_epochs: 100
crops:
  local_crops_size: 98